/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourceRouteImport } from './routes/source'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShareRouteImport } from './routes/share'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GaineRouteImport } from './routes/gaine'
import { Route as FindRouteImport } from './routes/find'
import { Route as DecreeRouteImport } from './routes/decree'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LearnCategoryIdArticleSlugRouteImport } from './routes/learn/$categoryId/$articleSlug'
import { Route as ApiReflectionRoutingRouteImport } from './routes/api/reflection/routing'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GaineRoute = GaineRouteImport.update({
  id: '/gaine',
  path: '/gaine',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const DecreeRoute = DecreeRouteImport.update({
  id: '/decree',
  path: '/decree',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCategoryIdArticleSlugRoute =
  LearnCategoryIdArticleSlugRouteImport.update({
    id: '/$categoryId/$articleSlug',
    path: '/$categoryId/$articleSlug',
    getParentRoute: () => LearnRoute,
  } as any)
const ApiReflectionRoutingRoute = ApiReflectionRoutingRouteImport.update({
  id: '/api/reflection/routing',
  path: '/api/reflection/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/decree': typeof DecreeRoute
  '/find': typeof FindRoute
  '/gaine': typeof GaineRoute
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/network': typeof NetworkRoute
  '/share': typeof ShareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/reflection/routing': typeof ApiReflectionRoutingRoute
  '/learn/$categoryId/$articleSlug': typeof LearnCategoryIdArticleSlugRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/decree': typeof DecreeRoute
  '/find': typeof FindRoute
  '/gaine': typeof GaineRoute
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/network': typeof NetworkRoute
  '/share': typeof ShareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/reflection/routing': typeof ApiReflectionRoutingRoute
  '/learn/$categoryId/$articleSlug': typeof LearnCategoryIdArticleSlugRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/decree': typeof DecreeRoute
  '/find': typeof FindRoute
  '/gaine': typeof GaineRoute
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/network': typeof NetworkRoute
  '/share': typeof ShareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/reflection/routing': typeof ApiReflectionRoutingRoute
  '/learn/$categoryId/$articleSlug': typeof LearnCategoryIdArticleSlugRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/decree'
    | '/find'
    | '/gaine'
    | '/impact'
    | '/learn'
    | '/marketplace'
    | '/network'
    | '/share'
    | '/sitemap.xml'
    | '/source'
    | '/admin/'
    | '/api/auth/google'
    | '/api/reflection/routing'
    | '/learn/$categoryId/$articleSlug'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/decree'
    | '/find'
    | '/gaine'
    | '/impact'
    | '/learn'
    | '/marketplace'
    | '/network'
    | '/share'
    | '/sitemap.xml'
    | '/source'
    | '/admin'
    | '/api/auth/google'
    | '/api/reflection/routing'
    | '/learn/$categoryId/$articleSlug'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/decree'
    | '/find'
    | '/gaine'
    | '/impact'
    | '/learn'
    | '/marketplace'
    | '/network'
    | '/share'
    | '/sitemap.xml'
    | '/source'
    | '/admin/'
    | '/api/auth/google'
    | '/api/reflection/routing'
    | '/learn/$categoryId/$articleSlug'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  DecreeRoute: typeof DecreeRoute
  FindRoute: typeof FindRoute
  GaineRoute: typeof GaineRoute
  ImpactRoute: typeof ImpactRoute
  LearnRoute: typeof LearnRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  NetworkRoute: typeof NetworkRoute
  ShareRoute: typeof ShareRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourceRoute: typeof SourceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiReflectionRoutingRoute: typeof ApiReflectionRoutingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaine': {
      id: '/gaine'
      path: '/gaine'
      fullPath: '/gaine'
      preLoaderRoute: typeof GaineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decree': {
      id: '/decree'
      path: '/decree'
      fullPath: '/decree'
      preLoaderRoute: typeof DecreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$categoryId/$articleSlug': {
      id: '/learn/$categoryId/$articleSlug'
      path: '/$categoryId/$articleSlug'
      fullPath: '/learn/$categoryId/$articleSlug'
      preLoaderRoute: typeof LearnCategoryIdArticleSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/api/reflection/routing': {
      id: '/api/reflection/routing'
      path: '/api/reflection/routing'
      fullPath: '/api/reflection/routing'
      preLoaderRoute: typeof ApiReflectionRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface LearnRouteChildren {
  LearnCategoryIdArticleSlugRoute: typeof LearnCategoryIdArticleSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnCategoryIdArticleSlugRoute: LearnCategoryIdArticleSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  DecreeRoute: DecreeRoute,
  FindRoute: FindRoute,
  GaineRoute: GaineRoute,
  ImpactRoute: ImpactRoute,
  LearnRoute: LearnRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  NetworkRoute: NetworkRoute,
  ShareRoute: ShareRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourceRoute: SourceRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiReflectionRoutingRoute: ApiReflectionRoutingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
